services:
  mysql:
    image: mysql:8.0
    container_name: mysql_accessappdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_accessappdb
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_accessapp
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass "tu_contraseña_segura"

  accessappuser:
    build:
      context: .
      dockerfile: Backend/AccessAppUser/Dockerfile
    container_name: accessappuser_api
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: AccessAppDb
      REDIS_CONNECTION: redis_accessapp:6379  # Adición de Redis a las variables de entorno
    ports:
      - "5000:80"
    depends_on:
      - mysql
      - redis # uso de Redis antes de iniciar el servicio
    volumes:
      - ./Backend/AccessAppUser:/app

volumes:
  mysql_data:
  redis_data:  # Volumen para Redis



